### ISSUE TITLE
Spanish copy for homepage

### ISSUE THREAD

**Issue by eljojo** [CovidShield/covidshield.github.io#18]
Hi everyone, I've done my best to translate the homepage into Spanish, it was much harder than anticipated.

Here's my copy:
```
COVID Shield is a free exposure notification solution built with privacy as its top priority. It was built by a group of volunteers in order to help Canadians and the rest of the world safely return to work.
COVID Shield es una solución libre para Exposure Notification enfocada en la privacidad. Fue creada por un grupo de voluntarios con el fin de ayudar a que Canadienses y el resto del mundo puedan volver seguros al trabajo.

(when it says free, is it free as in freedom?, can we translate as "an open source solution" instead? would sound better)

How can I download and use COVID Shield?
¿Cómo puedo descargar y usar COVID Shield?

COVID Shield is not currently available for download or use.
COVID Shield todavía no está disponible para descarga o uso.

COVID Shield is provided as a reference for your local public health authority to build their own app. If you are interested in using COVID Shield, please contact your local government representative and ask what they are doing about exposure notification for COVID-19.
COVID Shield se entrega como una base para que tus autoridades sanitarias locales puedan crear su propia app. Si estás interesado/a en usar COVID Shield, por favor contacta a tu gobierno local y pregúntales qué están haciendo al respecto de Exposure Notification para COVID-19.

COVID Shield is a private, secure, and easy-to-use tool to help governments launch their own exposure notification systems. It is based on the exposure notification technology provided by Apple and Google, the most privacy-preserving approach currently available.
COVID Shield es una herramienta privada, segura, y fácil de usar que ayuda a que gobiernos puedan lanzar su propio sistema de Exposure Notification. Está basada en la tecnología de Exposure Notification creada por Apple y Google, y es actualmente la implementación que más cuida la privacidad.

For exposure notification to be most effective, it is important that governments launch applications that can work together. COVID Shield is flexible enough to be deployed at various levels of government by enabling the server and mobile app to talk to each other even if there are multiple instances. 
Para que Exposure Notification sea más efectivo, es importante que los gobiernos creen aplicaciones que funcionen entre si. COVID Shield es lo suficientemente flexible para operar a varios niveles de gobierno, logra esto al permitir que la aplicación pueda comunicarse con servidores, incluso si hay más de uno.

The "COVID Shield is flexible enough" sentence is extremely hard to translate. When it refers to multiple instances, does it mean multiple servers/apps/both? It'd be great if the sentence could be split in two somehow or simplified. FWIW I suspect that part will not affect most spanish speaking countries, since (I believe) health is most commonly managed at the federal level.

Related reading
Links relacionados (en inglés)

    How does Exposure Notification work?
    ¿Cómo funciona Exposure Notification?
    Why is Exposure Notification important?
    ¿Por qué es Exposure Notification importante?
    Why use Apple and Google’s technology?
    ¿Por qué usar la tecnología de Apple y Google?


Privacy is our top priority 
La privacidad es nuestra prioridad #1

COVID Shield takes a privacy-first approach to exposure notification. The COVID Shield app, its server, and the web-based results portal are all designed to preserve personal privacy while helping people safely return to work. 
COVID Shield es Exposure Notification con un enfoque en la privacidad. La app de COVID Shield, su servidor, y el portal web están diseñados para mantener la privacidad individual y al mismo tiempo ayudar a la gente a volver de manera segura al trabajo.


Read our sample privacy policy
Lee nuestra política de privacidad de ejemplo

COVID Shield is made up of three parts: a mobile app, a server, and a web-based results portal. 
COVID Shield está compuesta por tres partes: una app móvil, un servidor, y un portal web para ver resultados.

We need a better translation for "a server", unsure how to translate without making it seem like we host it ourselves.


Mobile app (iOS and Android)
App Móvil (iOS y Android)

The mobile app runs in the background and requires no user interaction after onboarding. It uses Bluetooth to collect and share random IDs with nearby phones with COVID Shield installed. If a user tests positive for COVID-19, they can choose to anonymously share their data so others can be notified of possible exposure. Sharing of random IDs is voluntary and only possible with a positive test result confirmed by a health care professional. COVID Shield periodically downloads the shared random IDs from the server and compares them on each user’s device to determine if a possible exposure has occurred. 

La aplicación móvil siempre está funcionando y no requiere interación del usuario una vez configurada. Usa Bluetooth para recolectar y compartir IDs aleatorios con teléfonos cercanos que tengan COVID Shield instalado. Si un usario un exámen con resultado positivo, ellos/as pueden elegir comptartir sus IDs anónimamente para que otros usarios/as puedan ser notificados de una posible exposición. Compartir IDs aleatorias es voluntario y sólamente posible con resultado positivo confirmado por un profesional de la salud. COVID Shield descarga regularmente las IDs aleatorias compartidas a través del servidor y las compara con las alojadas en el celular para determinar si una posible exposición ha ocurrido.

I translated that they can share their IDs instead of their data ("share their data so others can"), is this correct? unsure how to translate their data without making it seem that it's their personal data

Server
Servidor

The server securely collects and stores random IDs uploaded from the mobile app after a confirmed positive test result. It also generates unique temporary codes which grant permission for people with a positive COVID-19 test result to upload their random IDs. The server is flexible enough to be deployed at various levels of government. 

El servidor recibe y almacena de manera segura las IDs aleatorias subidas a través de la app móvil después de haber confirmado un examen con resultado positivo. También genera códigos temporales únicos, que le permiten a usuarios subir sus IDs aleatorias al servidor en caso de examen positivo. El servidor es lo suficientemente flexible para ser implementado a varios niveles de gobierno.

Web portal
Portal de resultados Web

The web-based results portal provides health care professionals unique temporary codes which can be shared with users who have tested positive for COVID-19. This code gives a user access to upload their random IDs via the mobile app if they choose. No personal information is collected and there is no association between the codes and specific tests.

El portal web permite a profesionales de la salud generar códigos temporales que pueden ser compartidos con usuarios que han testeado positivo por COVID-19. Este código le permite a usuarios subir sus IDs aleatorias a través de la app web, si ellos deciden hacerlo. Ninguna información personal es recopilada y no hay asociación entre los códigos y resultados de exámenes.

Use of the portal is optional, as the server can also be used to generate temporary COVID Shield codes.
El uso del portal es opcional, ya que el servidor también puede ser usado para generar códigos de COVID Shield temporales.

Who built COVID Shield?
¿Quién creó COVID Shield?

We are a group of Shopify volunteers who want to help to slow the spread of COVID-19 by offering our skills and experience developing scalable, easy to use applications. We are releasing COVID Shield free of charge with a flexible open-source license.
Somos un grupo de voluntarios/as de Shopify que quieren ayudar a relentizar la propagación de COVID-19, ofreciendo nuestras habilidades y experincia desarrollando aplicaciones escalables que son fáciles de usar. Estmoas liberando COVID Shield libre de costo con una licencia open-source flexible.

For questions, we can be reached at press@covidshield.app 
Para preguntas, nos puedes contactar al correo press@covidshield.app
```

**Comment by eljojo** [comment]
@dfmcphee @emilybulger

**Comment by dfmcphee** [comment]
This is really great. Thanks so much for taking the time to do this @eljojo.

There are a couple more things I came across going through this. Would you be able to translate these as well?

## Breadcrumb
* `Return to homepage`

## Language selection
* `View page in`

## Notification example
* `now`
* `You have possibly been exposed to COVID-19`
* `Based on your random IDs, you have been near someone in the past 14 days who tested positive for COVID-19.`

**Comment by p0ns** [comment]
> COVID Shield is a free exposure notification solution built with privacy as its top priority. It was built by a group of volunteers in order to help Canadians and the rest of the world safely return to work.
> COVID Shield es una solución libre para Exposure Notification enfocada en la privacidad. Fue creada por un grupo de voluntarios con el fin de ayudar a que Canadienses y el resto del mundo puedan volver seguros al trabajo.

I'd translate Exposure Notification as "notificación de exposición" o "aviso de exposición" (al virus)

In regards of a "server" it should be more explicit, saying it's a "backend application" instead of a server, una "aplicación de servicio", o un "servicio web"

**Comment by emilybulger** [comment]
It looks like iOS is using "notificaciones de exposición al COVID-19" per https://github.com/CovidShield/mobile/issues/47, so we'll go with that. Thanks for the flag.

@honkfestival we use "Server" on frontend. I don't have opinion on "backend application" - can you weigh in? Thanks in advance.

**Comment by emilybulger** [comment]
Responding to @eljojo's questions:

> (when it says free, is it free as in freedom?, can we translate as "an open source solution" instead? would sound better)

We made choice to say both open source and free (as in gratis) for clarity and due to multiple audiences (general public, government, technical). It would be good to keep that consistency across languages.

> The "COVID Shield is flexible enough" sentence is extremely hard to translate. When it refers to multiple instances, does it mean multiple servers/apps/both? It'd be great if the sentence could be split in two somehow or simplified. FWIW I suspect that part will not affect most spanish speaking countries, since (I believe) health is most commonly managed at the federal level.

@honkfestival mind also adding detail here?

> We need a better translation for "a server", unsure how to translate without making it seem like we host it ourselves.

Sounds like we can resolve that in above comment. Thanks for flag.

> I translated that they can share their IDs instead of their data ("share their data so others can"), is this correct? unsure how to translate their data without making it seem that it's their personal data

It is not personally identifiable information, but there is a bit of technical complexity that is flattened on the frontend due to the language Apple/Google are using. "Data" here includes random IDs and, therefore, temporary exposure keys. It would be nice to mirror if possible, but I understand the concern.

**Comment by eljojo** [comment]
> We made choice to say both open source and free (as in gratis) for clarity and due to multiple audiences (general public, government, technical). It would be good to keep that consistency across languages.

I kept thinking about this. In Spanish we typically say [`software libre`](https://es.wikipedia.org/wiki/Software_libre) which conveys both `free` as in freedom and also open source. It's used to define software under Stallman's strict "free software" definition. Would it be okay if we used that instead? It doesn't imply use on any particular license (ie GPL and MIT are compatible, among others).

I'll take in the recommendations above and make a pull request for the homepage.

**Comment by honkfestival** [comment]
> @honkfestival we use "Server" on frontend. I don't have opinion on "backend application" - can you weigh in? Thanks in advance.

I think "backend application" is fine.

>  When it refers to multiple instances, does it mean multiple servers/apps/both? It'd be great if the sentence could be split in two somehow or simplified.

How about something like this:

COVID Shield can be deployed to accommodate different scenarios, including single app and backend application, or multiple apps sharing the same backend application.

**Comment by emilybulger** [comment]
Sorry for the delay. Coming back around to this today.

in English "server" is clear enough in context. In Spanish, less so. Specifically how you want to translate "backend server" is your call @eljojo 

I'm not an expert on Stallman's definition, by any means, but reading [this](https://www.gnu.org/philosophy/free-sw.en.html), can confirm that the expectation for COVID Shield usage is free as in both speech (freedom) and beer (price). That was a distinction we hoped to make as clear as possible, regardless of the audience.
